version: '3'

services:
  backend:
    image: hetic-tac-toe-backend:local
    container_name: backend
    ports:
      - 8000:8000
  frontend:
    image: hetic-tac-toe-frontend:local
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 8080:80

